fix: move wif functionality to PrivateKey
bitcoin-sv/go-sdk pull request #30
Opened 2024-06-05 18:17 UTC by shruggr

2024-06-05 22:47 UTC, sirdeggen requested changes
Looks good, please add a default

2024-06-05 22:47 UTC, sirdeggen commented on primitives/ec/privatekey.go
> +	a = append(a, net.PrivateKeyID)
Does this mean we have to drag around chainParams just to encode to Wif? I wish we could have default value in here somehow. Assume mainnet, but allow override.

2024-06-05 22:47 UTC, sirdeggen commented on primitives/ec/wif_test.go
> +	assert.Equal(t, mainWif, mainPriv.Wif(&chaincfg.MainNet))
This chaincfg.MainNet is a bit ugly. I recall thinking this stuff mattered when first using bsvjs - having the whole environment get set to a specific chain. Now I know it's literally just a prefix if you want to see it as a string, it feels like we can tuck it away somewhere.

2024-06-05 22:47 UTC, sirdeggen commented on primitives/ec/privatekey.go
> +	// Precalculate size.  Maximum number of bytes before base58 encoding
```suggestion
        if net == nil {
		net = &chaincfg.MainNet
	}
	// Precalculate size.  Maximum number of bytes before base58 encoding
```

2024-06-05 23:11 UTC, shruggr commented
I've removed chaincfg and implemented a default mainnet functionality.

2024-06-05 23:16 UTC, sirdeggen commented on primitives/ec/privatekey.go
> +	// Precalculate size.  Maximum number of bytes before base58 encoding
Would something like this work?

2024-06-06 15:45 UTC, shruggr commented on primitives/ec/privatekey.go
> +var (
I've removed chaincfg from this code entirely

2024-06-06 15:45 UTC, shruggr commented on primitives/ec/privatekey.go
> +func (p *PrivateKey) Wif() string {
Default to Mainnet

2024-06-06 15:46 UTC, shruggr commented on primitives/ec/privatekey.go
> +func (p *PrivateKey) WifPrefix(prefix byte) string {
Optional override

2024-06-06 20:46 UTC, sirdeggen approved these changes
Awesome thanks

2024-06-06 20:47 UTC, merged